[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first'
sort_imports = true

[profile.default]
solc_version = '0.8.25'
evm_version = 'Cancun'
libs = ['node_modules', 'lib']
optimizer_runs = 10_000

[profile.optimized]
via_ir = true
out = 'out-via-ir'

[profile.test]
via_ir = true
out = 'out-via-ir'

[profile.docs]
src = 'src/interfaces/'

[fuzz]
runs = 1000

[rpc_endpoints]
optimism = "${OPTIMISM_SEPOLIA_RPC}"
unichain = "${UNICHAIN_SEPOLIA_RPC}"

[etherscan]
optimism = { chain="11155420", key = "${OPTIMISM_EXPLORER_API_KEY}", url = "${OPTIMISM_EXPLORER_API}" }

